### ISSUE TITLE
Using nuget to install... Nothing happens

### ISSUE THREAD

**Issue by PabloRodriguezMontalvo** [sdesyllas/RiotApi.NET#19]
No reference dll, no new files... Visual Studio says is installed but cant use this

using RiotApi.Net.RestClient;
using RiotApi.Net.RestClient.Configuration;

"Cannot resolve symbol RiotApi"

**Comment by sdesyllas** [comment]
You are right, seems that the library is not installing well on projects that targeting .net framework 4.5.2 and above, will resolve it ASAP

**Comment by sdesyllas** [comment]
Deployed version 1.3.4 , the problem seems fixed

**Comment by PabloRodriguezMontalvo** [comment]
Perfect, now its correct.
