### ISSUE TITLE
MatchHistory.GetMatchHistoryBySummonerId not functioning?

### ISSUE THREAD

**Issue by baegmon** [sdesyllas/RiotApi.NET#23]
I'm currently trying to use the GetMatchHistoryBySummonerId function and I saw that there are two classes that can implement this (MatchList and MatchHistory).

When I use MatchList, it returns the correct values however when I use MatchHistory it just returns null so I was wondering if I'm doing something wrong? I've implemented the methods by how you've done it via ApiTests classes

    String rankType = "RANKED_SOLO_5x5";
    long playerID = 633123;
    var object = riotClient.MatchList.GetMatchListBySummonerId(RiotApiConfig.Regions.OCE, playerID, null, rankType);
     // works
    var object2 = riotClient.MatchHistory.GetMatchListBySummonerId(RiotApiConfig.Regions.OCE, playerID, null, rankType);
     // doesn't work

**Comment by sdesyllas** [comment]
I just checked the full reference of Riot and it seems like MatchHistory is not supported anymore and they removed it from the service references (https://developer.riotgames.com/api/methods). It seems like the only proper way to get the matches for a summoner Id is with the MatchList service.

I will remove the MatchHistory classes as they seem to be obsolete now.

**Comment by sdesyllas** [comment]
I will also link this issue #24 with changes for new mastery trees to be deployed with this version as well

**Comment by sdesyllas** [comment]
Check Pull Request #25

**Comment by sdesyllas** [comment]
done
