### ISSUE TITLE
JSON serialization error

### ISSUE THREAD

**Issue by PabloRodriguezMontalvo** [sdesyllas/RiotApi.NET#26]
var nombre_invocador = "insane Kumaì";

var datos_invocador = riotClient.Summoner.GetSummonersByName(RiotApiConfig.Regions.EUW, nombre_invocador).First().Value;

long id = datos_invocador.Id; //ID= 79978621

var otracosa = riotClient.MatchList.GetMatchListBySummonerId(RiotApiConfig.Regions.EUW, id); 
// This is when crashes for Json Serialization Error

Its my mistake or its because a API failure? I use the last version 1.40

**Comment by sdesyllas** [comment]
Hello , I replicated the problem and It seems an API failure, I will deploy a fixed version ASAP

**Comment by sdesyllas** [comment]
Version 1.4.1 that fixes this issue has been released on Nuget.
