### ISSUE TITLE
Match API JSON Serialization Error

### ISSUE THREAD

**Issue by tbrickey022** [sdesyllas/RiotApi.NET#29]
Hi!

I've been using this library to work on a project, but I ran into an issue when trying to retrieve information using the Match API.  The line I hit an issue with looks like this:

var mostRecentGame = riotClient.Match.GetMatchById(RiotApiConfig.Regions.NA, MostRecentMatchID); 

The error says "An exception of type 'RiotApi.Net.RestClient.Helpers.RiotExceptionRaiser.RiotApiException' occurred in RiotApi.Net.RestClient.dll but was not handled in user code"

It's also telling me there was a JSON serialization error.  Any thoughts?  

Thanks in advance!

**Comment by sdesyllas** [comment]
there are some new match type enums that seems that are not yet implemented.

check the file
https://github.com/sdesyllas/RiotApi.NET/blob/master/RiotApi.Net.RestClient/Helpers/Enums.cs
which are all the enums stored and add the enumeration that is missing. I
suppose that an enum is missing
from queuetype or matchmode.

I will appreciate if you could make a pull request for the fix

cheers



On Mon, Feb 22, 2016 at 3:03 AM, tbrickey022 <notifications@github.com>
wrote:

> Hi!
>
> I've been using this library to work on a project, but I ran into an issue
> when trying to retrieve information using the Match API. The line I hit an
> issue with looks like this:
>
> var mostRecentGame = riotClient.Match.GetMatchById(
> RiotApiConfig.Regions.NA, MostRecentMatchID);
>
> The error says "An exception of type
> 'RiotApi.Net.RestClient.Helpers.RiotExceptionRaiser.RiotApiException'
> occurred in RiotApi.Net.RestClient.dll but was not handled in user code"
>
> It's also telling me there was a JSON serialization error. Any thoughts?
>
> Thanks in advance!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sdesyllas/RiotApi.NET/issues/29>.
>



-- 
Spyros Desyllas
Software Engineer, MSc
*_____________________________________*

* <http://twitter.com/#%21/Desyllas>* <http://www.facebook.com/sdesyllas>
* <http://www.linkedin.com/in/sdesyllas> *

**Comment by DNA666777** [comment]
https://gyazo.com/59e9dc3edf7c358d98b4d875ae19b89d

The correction i cannot make a pull request for apply correction on masterbranch :/

**Comment by sdesyllas** [comment]
have you forked form my repository ?

On Fri, Feb 26, 2016 at 11:00 AM, DNA666777 <notifications@github.com>
wrote:

> https://gyazo.com/59e9dc3edf7c358d98b4d875ae19b89d
>
> The correction i cannot make a pull request for apply correction on
> masterbranch :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sdesyllas/RiotApi.NET/issues/29#issuecomment-189221704>
> .
>



-- 
Spyros Desyllas
Software Engineer, MSc
*_____________________________________*

* <http://twitter.com/#%21/Desyllas>* <http://www.facebook.com/sdesyllas>
* <http://www.linkedin.com/in/sdesyllas> *

**Comment by DNA666777** [comment]
i tried but i don't know how to use GitHub i use SVN normaly ^^'


2016-02-26 14:56 GMT+01:00 Spiros <notifications@github.com>:

**Comment by tbrickey022** [comment]
I think I've added DNA666777's change suggestions to the branch.  Let me know if there's anything else I can do to help!

**Comment by DNA666777** [comment]
DNA666777 is me :) . and this change work very well atm =>
https://gyazo.com/bbd8f0642713153ca371b11bec49c208

2016-02-26 22:10 GMT+01:00 tbrickey022 <notifications@github.com>:

**Comment by sdesyllas** [comment]
added the pull request and deployed new version on Nuget,
thanks a lot for your help!

On Fri, Feb 26, 2016 at 9:12 PM, DNA666777 <notifications@github.com> wrote:

> DNA666777 is me :) . and this change work very well atm =>
> https://gyazo.com/bbd8f0642713153ca371b11bec49c208
>
> 2016-02-26 22:10 GMT+01:00 tbrickey022 <notifications@github.com>:
>
> > I think I've added DNA666777's change suggestions to the branch. Let me
> > know if there's anything else I can do to help!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/sdesyllas/RiotApi.NET/issues/29#issuecomment-189484398>
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sdesyllas/RiotApi.NET/issues/29#issuecomment-189485098>
> .
>



-- 
Spyros Desyllas
Software Engineer, MSc
*_____________________________________*

* <http://twitter.com/#%21/Desyllas>* <http://www.facebook.com/sdesyllas>
* <http://www.linkedin.com/in/sdesyllas> *
