### ISSUE TITLE
The recently merged pull request hasn't been updated on the nuget package 1.2.1

### ISSUE THREAD

**Issue by Qinusty** [sdesyllas/RiotApi.NET#7]
The SpellVarsDto.Coeff is still IEnumerable\<bool\> on the latest nuget package (1.2.1). I have tried reinstalling the package however this did not fix the issue.

**Comment by sdesyllas** [comment]
Yes you are right , I replicated the problem. Seems something went wrong on nuget package process. I will push a new (1.2.2)

**Comment by sdesyllas** [comment]
I confirm that is ok now
