### ISSUE TITLE
Suggestion: Get rid of the external dependencies

### ISSUE THREAD

**Issue by khellang** [sdesyllas/RiotApi.NET#8]
**NB! This is just a suggestion, I don't mean to be rude. Feel free to disregard this :smile:**

Here's where I'm coming from...

I would never take a dependency on this library, simply because it has external dependencies on frameworks and tools that I don't know/like and don't normally use in my applications.
If every library had opinionated dependencies like this, we'd very quickly end up with 3-4 IoC containers and 2-3 logging frameworks in every application ever built. This is bad.

I would send a PR for this, but I'm currently swamped with other OSS work, so I'm leaving my suggestions on how to improve this for now:

**Logging**

Either remove (do you really need it?), or replace NLog with [LibLog](https://github.com/damianh/LibLog).
This is a drop-in .cs file, specifically created for library logging, which supports NLog, Log4Net, EntLib Logging, Serilog and Loupe, but makes it transparent to the user.

**Container**

Drop Ninject. It's not exactly a crazy complex object graph you're composing here. Forcing the user to take a dependency on Ninject for this is way too overkill.

I suggest the following API:
  - Keep the existing constructor for `RiotClient`, with all the dependencies.
  - Add a new constructor, without any dependencies, that will forward a call to the existing constructor with default implementations.

This'll allow you to remove the Ninject dependency and gives the user of the library the ability to choose their own, if any, container.

**JSON Serializer**

Consider this; A user already has a dependency on Newtonsoft.Json, but it's an older version that will de-/serialize JSON in different format than the version you've tested with and are depending on.
In .NET there can only be one version of a library loaded into the same AppDomain. If you're lucky, it's the version you're depending on and everything is fine (for your library, not necessarily for others). If you're not so lucky, you can end up with the older version, which will break the expected JSON schema and the library will fail. Not nice.

I suggest you replace the Newtonsoft.Json dependency with yet another single .cs file that you can drop into your project, namely [SimpleJson](https://github.com/facebook-csharp-sdk/simple-json). This can be internalized, configured and tweaked to match the exact schema that the API you're interacting with expects, without the user being able to change it, or other versions interfering :smile:

**Comment by sdesyllas** [comment]
Getting rid of the dependencies is something that bothered me lately and its something that I wanted to do in the first place. I will definitely implement your suggestions as they are reasonable and well explained.

* I will remove NLog completely as it is really not needed much.

* I will remove Ninject and let the library consumers to use whatever IoC container they want to.
I will keep the existing constructor and create a new one with no parameters that will make the call to the original constructor.

* I will investigate the Newtonsoft.Json dependency replacement with SimpleJson class

I will try to have a new pull request ready tomorrow to check it out.

Thanks for your effort and your suggestions to improve this library!

**Comment by khellang** [comment]
Cool! :+1: If you want some tips on customizing SimpleJson to your needs, you should take a look at https://github.com/octokit/octokit.net/blob/master/Octokit/Http/SimpleJsonSerializer.cs and github.com/khellang/Nancy.Swagger/blob/master/src/Swagger.ObjectModel/SwaggerModel.cs :smile:

**Comment by sdesyllas** [comment]
Replaced Newtonsoft.Json dependency with SimpleJson class file.
Added Riot serializer strategy that inherits the DataContract strategy for enum types handling.

**Comment by sdesyllas** [comment]
Check pull request #10

**Comment by khellang** [comment]
Closed by #10

**Comment by sdesyllas** [comment]
Version 1.3.0 is live on nuget , and thanks to you its a better dependency-free library !
